# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff3d11ac510a198e5bed59f4e8dd73a57e8de794ebf1b62615a25fabb15712670cfbde6f0c6638e1e7adedaf8eac988fc216b3017d8911ae701ff1f83ea75af

test:
  secret_key_base: b9f57230ccb2c8d07ce4b8069a3f62df51fc62015048d184425ce67f387fe147fbbf845b7b50998be6263340860b9f17bd70681f7c300e3d70ba4557a5ee6604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
